version: '3.9'

services:

  # api
  task_api:
    container_name: task_api
    image: task_api_bin
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: prod
    ports:
      - "8080:8080"